### ISSUE TITLE
Incorrect FSF address in COPYING and DISCLAIMER files

### ISSUE THREAD

**Issue by spstarr** [chaos/pdsh#100]
Hello pdsh developers,

I am a packager of pdsh for Fedora, I'm currently cleaning up the existing spec file we have and from checking, COPYING and DISCLAIMER are using the old FSF address.

If you could please adjust, grab the latest GPL 2 license from http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt 

Thanks,
Shawn

**Comment by grondo** [comment]
Sure, thanks for catching that!
