### ISSUE TITLE
pdcp, pdsh, rpdcp calling setuid and setgid without setgroups or initgroups

### ISSUE THREAD

**Issue by spstarr** [chaos/pdsh#101]
Is this intentional or should this be fixed up?

Thanks,
Shawn

**Comment by grondo** [comment]
pdsh should only be calling setuid/setgid to drop privileges when it is installed setuid root (hopefully packages aren't installed this way by default, it is only necessary for use of the rsh protocol and rresvport). I don't think setgroups or initgroups is warranted in this scenario, but I could be wrong.

Actually the drop of setuid privileges should be audited if it is kept at all.

**Comment by spstarr** [comment]
In our packaging none of the binaries are setuid root installed.

**Comment by grondo** [comment]
Ok, then these functions aren't used. However, I did open an issue #102 to ensure use of the functions is audited. I'll close this issue though.
