### ISSUE TITLE
history recall via readline, add appname

### ISSUE THREAD

**Issue by sdowdy** [chaos/pdsh#112]
So, i just did a pdsh to a bunch of machines to add a user manually with:

    pdsh> useradd ... -p '!!' username

in interactive mode, and unfortunately, '!!' got expanded to the last command i had previously done.  I guess i wasn't expecting that, not being completely familiar with readline having event expansion, but in trying to dig into how pdsh's readline integration works, i was hoping to setup something like:

    [~/.inputrc]
    $if Pdsh
      set history-size 0
    $endif

since pdsh uses its own `~/.pdsh/history` file.  Now, i could always do : 
    `pdsh() { INPUTRC=~/.pdsh/.inputrc command -p pdsh "$@" ;}`
or such, but i don't want to ;)

Yeah, i could also just build pdsh without readline support, but i actually do like to be able to do arrow-key recall on occasion, so this is more a thought experiment of allowing some users to override the system compiled selection of readline history.

It looks like libreadline uses an `extern const char* rl_readline_name` to define the application name that can be used in an $if conditional in `.inputrc`.

So, minimally, it'd be nice to add support in pdsh for that.

As a bit more backstory, in 'bash', i use 'set -H' and 'shopt histverify' so i can see a '!' event expansion command i'm about to run before i hit <ENTER>.   From looking at pdsh main.c interactive invocation loop, i don't think that would work w/o modifications anyway.  (i'd LOVE if that modification were added, though ;) ) 

But unless i'm missing something, i don't think libreadline has any event expansion control (i'd be happy to disable it, but keep line recall via arrow keys), but if anyone else knows of a way to get readline to disable event history expansion, but still allow arrow-key recall, please let me know.

Thanks,
--stephen

**Comment by grondo** [comment]
Sorry for letting this one languish so long.

It is simple to add the application name to realine, so I'll get that into the next release. It will be set to `basename (argv[0])` fyi.

I don't think you can have arrow key recall without a history, since there will be no history to recall. However, I don't have much experience with libreadline so I could be mistaken.
