### ISSUE TITLE
long outputs from hosts end up with garbled last few chars

### ISSUE THREAD

**Issue by smemsh** [chaos/pdsh#114]
for example this seems to work fine, all `a` at end no matter how many times it runs:
```
 $ pdsh -w scott "perl -e 'print \"a\" x 1000'" | od -aAn | tail -1
   a   a   a   a   a   a   a   a   a   a   a   a   a   a   a  nl
```
but take a look when increasing the size, the ending is always corrupted:
```
 $ for ((i = 0; i < 5; i++)); do pdsh -w scott "perl -e 'print \"a\" x 10000'" | od -aAn | tail -1; done
   a   a   a   a   a  sp   ^ etx   V   b del  nl
   a   a   a   a   a  sp  rs   0 esc   Q del  nl
   a   a   a   a   a  sp   n   D   V   Z del  nl
   a   a   a   a   a  sp  rs   D   6  rs del  nl
   a   a   a   a   a  sp  rs dc3   e etb del  nl
```
this never happens if (1) use ssh <host> <perlcmd> directly, or (2) execute directly on the remote system.

**Comment by grondo** [comment]
Ha. Nice find. This is a bug that only occurs when there's no newline and > 8191 bytes buffered. Try the following patch?

```diff
diff --git a/src/pdsh/dsh.c b/src/pdsh/dsh.c
index 6b7273f..7ff8933 100644
--- a/src/pdsh/dsh.c
+++ b/src/pdsh/dsh.c
@@ -578,9 +578,11 @@ static int _do_output (int fd, cbuf_t cb, out_f outf, bool 
 
 static void _flush_output (cbuf_t cb, out_f outf, thd_t *t)
 {
+    int n;
     char buf[8192];
 
-    while (cbuf_read (cb, buf, 8192) > 0) {
+    while ((n = cbuf_read (cb, buf, sizeof (buf) - 1)) > 0) {
+        buf[n] = '\0';
         if (t->labels)
             outf ("%S: %s\n", t->host, buf);
         else

```

This isn't a full fix though. pdsh doesn't handle output without newlines too well, and in this case some newlines will be inserted every 8191 bytes, even with `-N`. However, at least we're not reading from uninitialized memory anymore.

**Comment by grondo** [comment]
or try pr #115

**Comment by smemsh** [comment]
seems to work fine with `grondo/issue#114`, all rows are clean `a` chars.  extra newlines every 8k might explain some puzzling discrepancies I've seen in the past too... thanks!
