### ISSUE TITLE
Source Relases don't build

### ISSUE THREAD

**Issue by knusbaum** [chaos/pdsh#116]
The source talballs in the Relases section of the github don't build. They don't include a working `configure` script, and the `bootstrap` script does not work on account of the tarball not containing a valid git repository. 
The configure.ac file depends on git here: https://github.com/chaos/pdsh/blob/master/configure.ac#L10

**Comment by grondo** [comment]
In preparation for a new release I double checked that the latest release tarball does indeed include a working `./configure` and can be built outside of git.

Make sure that you download the uploaded release tarball:

 https://github.com/chaos/pdsh/releases/download/pdsh-2.33/pdsh-2.33.tar.gz

and *not* the github tarball that is autogenerated from the tag:

 https://github.com/chaos/pdsh/archive/pdsh-2.33.tar.gz

I'm not sure if those automated tarballs can be disabled.
