### ISSUE TITLE
Please publish a new release 2.33

### ISSUE THREAD

**Issue by jurobystricky** [chaos/pdsh#118]
As it has been over two years since the last release of pdsh (2.32 released this on June 28, 2017) it would be nice if you would publish a new release 2.33 reflecting the current master branch. This would make life easier for many Linux distribution packagers by not having to backport  relevant patches from master to the latest release. It would also re-affirm that pdsh is actively maintained. Project being actively maintained is one of the major criterias whether to include a package in a Linux distribution or not.
BTW, I am aware that it is possible to build packages based on any particular commit (i.e. master), however it is preferable to use an official release with as few changes as possible.
Thanks.

**Comment by grondo** [comment]
Sounds good, will probably try to get #115 merged first, then tag.

**Comment by jurobystricky** [comment]
Sounds good to me as well. Thanks for the quick reply.

**Comment by grondo** [comment]
New release issued [pdsh-2.34](https://github.com/chaos/pdsh/releases/tag/pdsh-2.34).

Please let us know if there's any problems.
