### ISSUE TITLE
Wrong News link in 2.34 release 

### ISSUE THREAD

**Issue by MrBr-github** [chaos/pdsh#121]
Hi @grondo 
There is a small issue in [releases](https://github.com/chaos/pdsh/releases)
The **View latest NEWS** link points to 2.33 news instead of 2.34

P.S. thanks for a great tool :)

**Comment by grondo** [comment]
Ah, bummer and thanks for the catch!  I'll fix it manually

**Comment by grondo** [comment]
Ok, fixed. Thanks!
