### ISSUE TITLE
racadm and ipmitool?

### ISSUE THREAD

**Issue by dylex** [chaos/pdsh#125]
I've been using `pdsh -R exec` to run the racadm (idracadm7, dell's remote management) command (and I suppose ipmitool would function similarly), but quoting can get a bit messy sometimes.  I realized it should be fairly easy to write rcmd modules for these.  I'm happy to work up a PR if this would be of interest, though realize it also may be a bit out of scope (and maybe too trivial).

**Comment by grondo** [comment]
That's a neat use case for the `exec` module, thanks! I don't see a reason not to merge a PR -- I'm not sure what other pdsh maintainers would think. Some thoughts, though:

 - I wonder if there are any simple improvements that could be made to the `exec` module to make things easier? It might help to see an example of your use case.
 - Would it be possible to make a script that wraps racadm or ipmitool to work around the shell quoting issues instead?

**Comment by dylex** [comment]
> * I wonder if there are any simple improvements that could be made to the `exec` module to make things easier? It might help to see an example of your use case.

It's not actually that bad, really now that I've gone through it (my initial attempts were probably unnecessarily complicated):
`pdsh -R exec ... racadm -r %h -u %u -p $passwd set ...`

> * Would it be possible to make a script that wraps racadm or ipmitool to work around the shell quoting issues instead?

This is exactly what I'm doing now for automated things, but interactively it's not as convenient.

**Comment by chu11** [comment]
> That's a neat use case for the exec module, thanks! I don't see a reason not to merge a PR

It does open a potential can of worms.  If there's a racadm and ipmitool rcmd module, would we also want an ipmiutil, freeipmi, ilo, etc. ones too?  Perhaps there's a subtlety I'm missing.

**Comment by dylex** [comment]
Now that I'm thinking about it I suppose I could just write a shell function to do most of what I want just as well, which is perhaps a more reasonable solution.  Maybe just another example in the man page would help.
