### ISSUE TITLE
dshbak Errors on Empty Input

### ISSUE THREAD

**Issue by negregg** [chaos/pdsh#132]
The update to version 2.34 breaks dshbak when it is passed empty input.  While it might not make sense to pass empty/null information to dshbak, this is not uncommon when it is used in scripts, etc. which is how we found the issue.

Example error:
```
echo "" | dshbak -c
Use of uninitialized value $tag in string at /usr/bin/dshbak line 115, <> line 1.
```

The issue appears to be with recent modification on line 115.
```
diff ./dshbak.old ./dshbak.new
115c115
< 		next unless "$tag" ne "";
---
> 		next unless $tag;
```

**Comment by grondo** [comment]
Good find. I guess the right fix should have been something like
```diff
diff --git a/scripts/dshbak b/scripts/dshbak
index a6e17eb..fbb4e71 100755
--- a/scripts/dshbak
+++ b/scripts/dshbak
@@ -112,7 +112,7 @@ sub process_lines
        while (<>) {
                my ($tag, $data) = m/^\s*(\S+?)\s*: ?(.*\n)$/;
                #  Ignore lines that aren't prefixed with a hostname:
-               next unless "$tag" ne "";
+               next unless defined $tag and "$tag" ne "";
                push(@{$lines{$tag}}, $data);
        }
```

**Comment by grondo** [comment]
I'll add a test to `t5000-dshbak.t` to ensure we don't regress this issue again and push up a PR with the fix above. Thanks!

**Comment by negregg** [comment]
@grondo Thanks for the very quick review and fix.  Much appreciated!
