### ISSUE TITLE
A possible deadlock issue in the cbuf_copy

### ISSUE THREAD

**Issue by jenny-cheung** [chaos/pdsh#136]
Dear Developers:
  Thank you for your checking. The function cbuf_copy is concurrently executed, would it lead to a deadlock due to the cyclic order on lock acquisitions?

```
int
cbuf_copy (cbuf_t src, cbuf_t dst, int len, int *ndropped)
{
   ...
    /*  Lock cbufs in order of lowest memory address to prevent deadlock.
     */
    if (src < dst) {
        cbuf_mutex_lock(src);
        cbuf_mutex_lock(dst);
    }
    else {
        cbuf_mutex_lock(dst);
        cbuf_mutex_lock(src);
    }
    ...;
    cbuf_mutex_unlock(src);
    cbuf_mutex_unlock(dst);
    return(n);
}
```

Best,

**Comment by jenny-cheung** [comment]
Sorry for my unclear description. When the function is executed by two concurrent threads, would it lead to a deadlock? Because there is a cyclic order on the two locks src and dst.

**Comment by grondo** [comment]
I will have to review code, but I think in `pdsh` cbufs are not shared between threads so there is no potential deadlock.

**Comment by jenny-cheung** [comment]
@grondo Hi, thank you very much for your reply.
If this function is not shared between threads, it is fine and would not lead to deadlock. But this thread function is indeed not thread-safe and this potential error is worth fixing. Maybe one day this function is involved mistakenly by different threads or the related code is copied to another concurrent function that can trigger a real deadlock in pdsh. 

According to the [lock discipline](https://docs.oracle.com/cd/E18752_01/html/816-5137/guide-35930.html) to avoid deadlock, saying "when using multiple locks, avoid deadlocks by making sure that all threads acquire the locks in the same order".

 I like pdsh and commonly use it, would like to improve its reliability. If you think the code could be improved to avoid such potential error, I am very happy to create a PR!

Best,

**Comment by chu11** [comment]
> According to the lock discipline to avoid deadlock, saying "when using multiple locks, avoid deadlocks by making sure that all threads acquire the locks in the same order".

Aren't the locks being acquired in the same order?  The `if (src < dst)` address check protects this?

For example, in the below, aren't the locks acquired in the same order in both cases?

```C
cbut_t a = ...;
cbuf_t b = ...;

// in thread 1
cbuf_copy (a, b, ...);

// in thread 2
cbuf_copy (b, a, ...);
```

maybe i'm missing something.

**Comment by jenny-cheung** [comment]
@chu11 Thank you for your reply. I forget to check the related branch conditions.

**Comment by grondo** [comment]
Thanks @chu11! Thanks @jenny-cheung for looking after our code quality! :slightly_smiling_face:
