### ISSUE TITLE
A lock threadcount_mutex is not relesed?

### ISSUE THREAD

**Issue by ycaibb** [chaos/pdsh#137]
Hi, thank you for your checking. Does it seem the lock `threadcount_mutex ` is not released? It could be problematic, leading to bugs like a deadlock. Looking forward to the discussion!

https://github.com/chaos/pdsh/blob/e5fdb558985a897d3aa65b9e73f73c89f6bfbfa9/src/pdsh/dsh.c#L1192

https://github.com/chaos/pdsh/blob/e5fdb558985a897d3aa65b9e73f73c89f6bfbfa9/src/pdsh/dsh.c#L1192-L1228

**Comment by grondo** [comment]
Yes, `threadcount_mutex` is not released. However, at this point in `pdsh` the global `threadcount` variable is no longer used, so there is technically no reason for the `dsh()` function to release the mutex. Any future use of `threadcount` or `threadcount_mutex` would be  a bug.

**Comment by ycaibb** [comment]
@grondo Thank you for your reply. Would be safer to release the mutex at the end of `dsh()`? It is cheap to take precautions for any dangerous errors in the future. Would you mind I create a PR for this?

**Comment by grondo** [comment]
You could release the mutex right after the while loop returns. Though probably unnecessary, I would accept a PR that did that since `threadcount` is not accessed after that point and therefore no longer needs to be protected by the mutex.

**Comment by grondo** [comment]
Fixed by #138
