### ISSUE TITLE
Early exit if one/some host returns with non-zero error code

### ISSUE THREAD

**Issue by jerrymannil** [chaos/pdsh#139]
I have a scenario where commands returned with non-zero value in some hosts; but other hosts are still running the command.
Is there are option to early exit in this case ?

**Comment by grondo** [comment]
No, I think the only thing close would be to add a "command timeout" with the `-u seconds` option.

**Comment by jerrymannil** [comment]
Is it possible to add support for this ?
I see an option already exist in [opt.h](https://github.com/chaos/pdsh/blob/master/src/pdsh/opt.h#L72). 
Does this option work ?. 
If so, I think we just need to add a command line option to enable it.

**Comment by grondo** [comment]
I believe that the `kill_on_fail` option was introduced when `pdsh` used to be able to launch parallel MPI jobs on the Elan interconnect using the `qshell` method. I'm not sure if the option will work during normal `pdsh` operation when there is a sliding window of threads.

I would encourage you to try it out though! It may work. Try registering a new `-k` option that sets `kill_on_fail` to true and then try various test cases and let us know how it works for you!

Thanks for noticing that old option, I had forgotten about it.

**Comment by jerrymannil** [comment]
Sure, will give that a try.
Thanks.
