### ISSUE TITLE
slurm: compilation error against Slurm >= 23.x

### ISSUE THREAD

**Issue by grondo** [chaos/pdsh#152]
The pdsh `slurm` module currently contains a workaround for including `slurm.h` since it exports an internal `List` interface:

https://github.com/chaos/pdsh/blob/3bc95a8d7567d9f7039dc2c16e37820dbff69e06/src/modules/slurm.c#L44-L54

Recent versions of Slurm _expanded_ this interface with additional typedefs for `struct xlist` `list_t` and `list_iterator_t` for the iterator.

This means the current workaround no longer works, since we can't let Slurm redefine our internal `List`, but we have to let them define their duplicate typedef `list_t`. Also, I noticed that the redefinition of `hostlist_t` now also causes problems, so `__hostlist_t_defined` also needs to be exported :shrug: .

The following patch seems to workaround these issues for now, though it is probably brittle in the long term. 

```diff
diff --git a/src/modules/slurm.c b/src/modules/slurm.c
index 5594c4f..c227337 100644
--- a/src/modules/slurm.c
+++ b/src/modules/slurm.c
@@ -50,6 +50,16 @@
  *  with our internal List datatype.
  */
 #define __list_datatypes_defined 1
+/*
+ * Also, Slurm>=23.x requires that `struct xlist` be typedef'd to list_t:
+ */
+typedef struct xlist list_t;
+typedef struct listIterator list_itr_t;
+/*
+ * Also, Slurm exports the hostlist_t interface as well:
+ */
+#define __hostlist_t_defined 1
+
 #include <slurm/slurm.h>
 #include <slurm/slurm_errno.h>
```

**Comment by boegel** [comment]
FWIW: This is how the error manifests itself (with pdsh 2.34 + Slurm 23.02.6), just so people can easily find the associated fix in #153:
```
In file included from slurm.c:53:
/usr/include/slurm/slurm.h:1393:31: error: unknown type name list_t; did you mean List?
 1393 | extern void slurm_list_append(list_t *l, void *x);
      |                               ^~~~~~
      |                               List
```
