### ISSUE TITLE
pdsh can't find modules if installed in $HOME

### ISSUE THREAD

**Issue by ghost** [chaos/pdsh#75]
If pdsh is configured with `./configure --prefix $HOME` it still looks for modules in `/usr/local/lib/pdsh`:

```
$ pdsh
pdsh@hostname: Can't stat "/usr/local/lib/pdsh": No such file or directory
pdsh@hostname: Couldn't load any pdsh modules
```

**Comment by grondo** [comment]
Hm, sorry about that, did you use any other args to `./configure`?
Was this after `make install`, and can you verify `pdsh` found above is `$HOME/bin/pdsh` by running `which pdsh`?

**Comment by okuzminskyi** [comment]
Mark,

it was just `./configure --prefix $HOME`. `pdsh` was installed in `$HOME/bin` as expected.
By the way, `./configure --prefix $HOME --with-ssh` fixed my problem.

**Comment by grondo** [comment]
Ah, I wonder if there were *no* modules installed at all and that was the problem.

**Comment by okuzminskyi** [comment]
yes, that was the problem. The error message confused me.

**Comment by grondo** [comment]
Ok, sorry about that! We should perhaps have `make install` install an empty directory -- that would improve/remove the error.
