### ISSUE TITLE
exec module not passing arguments correctly?

### ISSUE THREAD

**Issue by brianjmurrell** [chaos/pdsh#92]
So I want to use the _exec_ module to effect a command for the specified hosts.  The command being specified is a _Ruby_ script.

But what I'm finding is that Ruby's option parser is not seeing the options as being given by `pdsh` the same as it does from a regular shell command-line execution:

```
$ /tmp/ruby_arg foo -c bar
foo
$ pdsh -R exec -w node1 /tmp/ruby_arg foo -c bar
node1: foo
node1: -c
node1: bar
```

Notice that when run from `pdsh -R exec` the script doesn't parse any of the options but when executed directly it does, returning the only argument without an option.

The Ruby script being run is:

```
#!/usr/bin/ruby

require 'optparse'

options = {}

opts = OptionParser.new do |o|
  o.banner = "Usage: [options] name "
  o.separator ""
  o.separator "Options:"
  o.separator ""

  o.on("-c", "--command COMMAND", "Command") do |c|
    options[:command] = c
  end

  o.on("-p", "--plain", "Plain mode") do |p|
    options[:plain_mode] = p
  end
end

argv = ARGV.dup

opts.parse!(argv)

puts(argv)
```

I wonder if anything jumps to mind about what pdsh might be doing with the arguments and how it's execve()ing them that the shell would be doing differently?

**Comment by brianjmurrell** [comment]
So, the difference seems to be whether POSIXLY_CORRECT is set in the environment or not:

```
$ /tmp/ruby_arg foo -c bar
!POSIXLY_CORRECT
foo
$ POSIXLY_CORRECT=1 /tmp/ruby_arg foo -c bar
POSIXLY_CORRECT
foo
-c
bar
```

**Comment by grondo** [comment]
Heh, good catch.

Pdsh sets POSIXLY_CORRECT to avoid permuting options, however, it shouldn't export that to its subcommands I suppose!

**Comment by brianjmurrell** [comment]
Sounds reasonable to not export that I think.

**Comment by grondo** [comment]
Feel free to submit a patch, I think for GNU getopt instead of POSIXLY_CORRECT the optstring can begin with "+" or something similar. If you don't have time I'll try to get something in later this week.

**Comment by brianjmurrell** [comment]
So yes, I have been reading about starting with "+" but I can't seem to work out what that really means.  Anything I try seems to result in a failure to parse and I get "no remote hosts specified".

I can submit a patch of course, but unless I also roll my own RPMs an fix will be less than immediate.  I'm hoping I can utilise "+" as an immediate work-around while I wait for the fix to trickle out to distros.

**Comment by brianjmurrell** [comment]
Hrm, wait.  "+" isn't going to help me here in any way.  I guess I'm rolling my own RPMs for the time being.  :-(

**Comment by grondo** [comment]
Sorry, you could also be sure to put all options first in your ruby invocation so that the POSIXLY_CORRECT doesn't affect option ordering, i.e.

```
 pdsh -R exec -w node1 /tmp/ruby_arg -c bar foo
```

I know, less than optimal...

**Comment by brianjmurrell** [comment]
Lol.  Of course.  I think I can work with that in the meanwhile.

Thanks for the suggestion!

**Comment by grondo** [comment]
Hm, also interesting, pdsh does already try to unset POSIXLY_CORRECT after options parsing, I wonder why/if this isn't working?

```C
/*
 *  Process any options that need to be handled early, i.e.
 *   before modules are loaded.
 */
void opt_args_early (opt_t * opt, int argc, char *argv[])
{
    int c;
    extern int optind;
    extern char *optarg;
    extern int opterr;
    int pc = 0;

    /*
     *  Disable error reporting from getopt during early processing,
     *   since we won't have access to all the options provided by
     *   dlopened modules.
     */
    opterr = 0;

#ifdef __linux
    if (!getenv("POSIXLY_CORRECT")) {
        /* Tell glibc getopt to stop eating after the first non-option arg */
        putenv("POSIXLY_CORRECT=1");
        pc = 1;
    }
#endif
    while ((c = getopt(argc, argv, pdsh_options)) != EOF) {
        switch (c) {
            case 'M':
                if (opt->misc_modules)
                    Free ((void **) &opt->misc_modules);
                opt->misc_modules = Strdup (optarg);
                break;
        }
    }
#ifdef __linux
    if (pc) {
        unsetenv("POSIXLY_CORRECT");
    }
#endif
}
```

**Comment by grondo** [comment]
Ah, that code didn't enter until 72ac48528181d80a159be0c8b8f52d82769d9aeb, so I think this issue is fixed upstream (in pdsh-2.31)?

@brianjmurrell, what version do you happen to be running?

**Comment by brianjmurrell** [comment]
pdsh-2.31-6.fc24.x86_64

**Comment by grondo** [comment]
Oh, oops I didn't read the history right. Sadly, this change didn't make it into any tags yet
